version: "3"
services:
  database-phpd:
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    ports:
      - 3320:3306
    volumes:
      - db-data-phpd:/var/lib/mysql
    container_name: database-phpd
  webserver-phpd:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 86:80
      - 4438:443
    volumes:
      - ./:/var/www/html
    container_name: webserver-phpd
    depends_on:
      - database-phpd
    links:
      - database-phpd:database-phpd
volumes:
  db-data-phpd: {}
